/**
 * hosted-packet-builder.ts — Assembles and encrypts a hosted legacy packet.
 *
 * ALPHA KEY MANAGEMENT NOTE:
 * In the v1 hosted model, server-side trusted encryption is used. The packetKey
 * generated by encryptPacketPayload() is encrypted with the server field
 * encryption key and persisted so the hosted claim flow can present release
 * material after the contact completes the required access steps.
 *
 * SECURITY: The payload MUST NOT include passwordHash, sessionId,
 * stripeCustomerId, API keys, storage credentials, Postmark tokens,
 * Telegram bot tokens, or claimPinHash.
 */

import { randomUUID } from 'crypto';
import { eq, inArray } from 'drizzle-orm';
import type { AegisDb } from '../db/index.js';
import { estateItems, contacts, switches, users } from '../db/schema.js';
import { decryptEstateItem } from './estate-mapper.js';
import { decryptContact } from './contact-mapper.js';
import { encryptPacketPayload } from './packet-crypto.js';
import { encryptField } from './field-encrypt.js';
import { createPacket, updatePacketStorage } from '../repositories/packet-repository.js';
import { uploadManagedPacket } from './storage/index.js';
import { PacketEnvelopeSchema } from '@aegis-site/contracts';
import type { AppConfig } from '../config.js';

// ── Payload types ─────────────────────────────────────────────────────────────

export interface HostedPacketPayload {
  schemaVersion: '1';
  sourceApp: 'aegis_hosted';
  generatedAt: string;
  owner: {
    displayName: string;
  };
  switchSummary: {
    id: string;
    name: string;
    mode: string;
  };
  estateItems: Array<{
    id: string;
    category: string;
    title: string;
    institutionName: string | null;
    accountType: string | null;
    referenceHint: string | null;
    assetDescription: string | null;
    locationNotes: string | null;
    executorNotes: string | null;
  }>;
  contacts: Array<{
    id: string;
    fullName: string;
    relationship: string | null;
    email: string;
    phone: string | null;
    telegramHandle: string | null;
    priorityOrder: number;
    confirmationWindowHours: number;
  }>;
  releaseDisclaimers: string[];
}

// ── Builder input/output ──────────────────────────────────────────────────────

export interface BuildHostedPacketInput {
  userId: string;
  switchId: string;
  releaseRunId: string;
  db: AegisDb;
  config: AppConfig;
}

export interface BuildHostedPacketResult {
  packetId: string;
  version: number;
  keyId: string;
  contentHash: string;
  encryptedObjectHash: string;
  storageObjectKey: string;
}

// ── Main builder ──────────────────────────────────────────────────────────────

export async function buildHostedPacket(
  input: BuildHostedPacketInput,
): Promise<BuildHostedPacketResult> {
  const { userId, switchId, releaseRunId, db, config } = input;

  // ── Step 1: Load switch, user, estate items, and contacts ─────────────────

  // Load switch record to get name, mode, selectedEstateItemIds, selectedContactIds
  const switchRows = await db
    .select()
    .from(switches)
    .where(eq(switches.id, switchId));

  if (switchRows.length === 0) {
    throw new Error(`Switch not found: ${switchId}`);
  }
  const sw = switchRows[0];

  // Load user display name
  const userRows = await db
    .select({ displayName: users.displayName })
    .from(users)
    .where(eq(users.id, userId));

  if (userRows.length === 0) {
    throw new Error(`User not found: ${userId}`);
  }
  const userDisplayName = userRows[0].displayName;

  // Resolve selected estate item IDs
  const selectedEstateItemIds = (
    Array.isArray(sw.selectedEstateItemIds) ? sw.selectedEstateItemIds : []
  ) as string[];

  // Resolve selected contact IDs
  const selectedContactIds = (
    Array.isArray(sw.selectedContactIds) ? sw.selectedContactIds : []
  ) as string[];

  // Load estate items
  let estateItemRows: (typeof estateItems.$inferSelect)[] = [];
  if (selectedEstateItemIds.length > 0) {
    estateItemRows = await db
      .select()
      .from(estateItems)
      .where(inArray(estateItems.id, selectedEstateItemIds));
  }

  // Load contacts
  let contactRows: (typeof contacts.$inferSelect)[] = [];
  if (selectedContactIds.length > 0) {
    contactRows = await db
      .select()
      .from(contacts)
      .where(inArray(contacts.id, selectedContactIds));
  }

  // ── Step 2: Decrypt estate/contact fields ─────────────────────────────────

  const encryptionKey = config.fieldEncryptionKey;

  const decryptedEstateItems = estateItemRows.map((row) =>
    decryptEstateItem(row, encryptionKey),
  );

  const decryptedContacts = contactRows.map((row) =>
    decryptContact(row, encryptionKey),
  );

  // ── Step 3: Assemble HostedPacketPayload ──────────────────────────────────

  // SECURITY: payload deliberately excludes passwordHash, stripeCustomerId,
  // subscription details, API keys, storage credentials, Postmark tokens,
  // Telegram bot tokens, claimPinHash, and session information.

  const payload: HostedPacketPayload = {
    schemaVersion: '1',
    sourceApp: 'aegis_hosted',
    generatedAt: new Date().toISOString(),
    owner: {
      displayName: userDisplayName,
    },
    switchSummary: {
      id: sw.id,
      name: sw.name,
      mode: sw.mode,
    },
    estateItems: decryptedEstateItems.map((item) => ({
      id: item.id,
      category: item.category,
      title: item.title,
      institutionName: item.institutionName,
      accountType: item.accountType,
      referenceHint: item.referenceHint,
      assetDescription: item.assetDescription,
      locationNotes: item.locationNotes,
      executorNotes: item.executorNotes,
    })),
    contacts: decryptedContacts.map((c) => ({
      id: c.id,
      fullName: c.fullName,
      relationship: c.relationship,
      email: c.email,
      phone: c.phone,
      telegramHandle: c.telegramHandle,
      priorityOrder: c.priorityOrder,
      confirmationWindowHours: c.confirmationWindowHours,
    })),
    releaseDisclaimers: [
      'This packet contains legacy information intended for release only upon confirmed death or incapacitation.',
      'Recipients must verify their identity before accessing the contents.',
    ],
  };

  // ── Step 4: Encrypt payload ───────────────────────────────────────────────

  const cryptoResult = encryptPacketPayload(payload);

  const packetKeyEncrypted = encryptField(
    cryptoResult.packetKey.toString('base64'),
    config.fieldEncryptionKey,
  );

  // ── Step 5: Generate and validate PacketEnvelope ──────────────────────────

  const packetId = randomUUID();
  const version = 1;

  const envelope = PacketEnvelopeSchema.parse({
    version: 1,
    packetId,
    switchId,
    userId,
    sourceApp: 'aegis_hosted',
    encryptionAlgorithm: 'aes-256-gcm',
    keyId: cryptoResult.keyId,
    contentHash: cryptoResult.contentHash,
    createdAt: new Date().toISOString(),
  });

  // ── Step 6: Insert packet metadata (pre-storage, without storage details) ─

  const packetRecord = await createPacket(db, {
    userId,
    switchId,
    releaseRunId,
    relayConnectionId: null,
    sourceApp: envelope.sourceApp,
    schemaVersion: '1',
    version,
    encryptionAlgorithm: envelope.encryptionAlgorithm,
    keyId: envelope.keyId,
    packetKeyEncrypted,
    contentHash: envelope.contentHash,
    encryptedObjectHash: cryptoResult.encryptedObjectHash,
    storageProvider: null,
    storageBucket: null,
    storageObjectKey: null,
    storageRegion: null,
    storageVersionId: null,
    lastVerifiedAt: null,
    expiresAt: null,
  });

  // ── Step 7: Upload encrypted data to managed storage ─────────────────────

  const uploadResult = await uploadManagedPacket({
    userId,
    releaseRunId,
    packetId: packetRecord.id,
    version,
    encryptedData: cryptoResult.encryptedData,
    encryptedObjectHash: cryptoResult.encryptedObjectHash,
    config: config.storage,
  });

  // ── Step 8: Update packet record with storage details ─────────────────────

  await updatePacketStorage(db, packetRecord.id, {
    storageProvider: uploadResult.storageProvider,
    storageBucket: uploadResult.storageBucket,
    storageObjectKey: uploadResult.storageObjectKey,
    storageRegion: uploadResult.storageRegion,
    storageVersionId: uploadResult.storageVersionId ?? undefined,
    lastVerifiedAt: uploadResult.lastVerifiedAt,
  });

  // ── Step 9: Return result ─────────────────────────────────────────────────

  return {
    packetId: packetRecord.id,
    version,
    keyId: cryptoResult.keyId,
    contentHash: cryptoResult.contentHash,
    encryptedObjectHash: cryptoResult.encryptedObjectHash,
    storageObjectKey: uploadResult.storageObjectKey,
  };
}
